name: Release

on:
  push:
    branches: [main]
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build-musl:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-musl
            image: rust-musl-cross:x86_64-musl
          - target: aarch64-unknown-linux-musl
            image: rust-musl-cross:aarch64-musl
          - target: armv7-unknown-linux-musleabihf
            image: rust-musl-cross:aarmv7-musleabihf
    container:
      image: docker://ghcr.io/rust-cross/${{ matrix.image }}
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: ./scripts/build.sh ${{ matrix.target }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: yazi-${{ matrix.target }}.zip
          path: yazi-${{ matrix.target }}.zip


  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: [build-musl]
    steps:
      - uses: actions/download-artifact@v4
        with:
          merge-multiple: true

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          files: |
            yazi-*.zip
            yazi-*.snap
          generate_release_notes: true
